In [5]:
import random
import numpy as np

In [6]:
weights = np.array([87, 66, 70, 25, 33, 24, 89, 63, 23, 54])
values = np.array([96, 55, 21, 58, 41, 81, 8, 99, 59, 62])

N = len(weights)
SEED = 32767

In [20]:
def search(weights, values, max, limit):
    maxvalue = 0
    ret = None
    for _ in range(limit):
        bits = (np.random.randn(N) * 2 > 0.5).astype(int)
        weight = np.sum(weights * bits)
        if weight > max:
            value = 0
        else:
            value = np.sum(values * bits)
        if value > maxvalue:
            maxvalue = value
            ret = bits
    print(maxvalue)
    print(ret)

In [21]:
LIMIT = 200
MAX =250
np.random.seed(SEED)
for _ in range(10):
    search(weights, values, MAX, LIMIT)

393
[1 0 0 1 0 1 0 1 1 0]
356
[0 1 0 0 0 1 0 1 1 1]
356
[1 0 0 1 0 1 0 0 1 1]
356
[0 1 0 0 0 1 0 1 1 1]
356
[0 1 0 0 0 1 0 1 1 1]
352
[0 1 0 1 0 1 0 1 1 0]
400
[0 0 0 1 1 1 0 1 1 1]
339
[1 0 0 0 1 1 0 0 1 1]
393
[1 0 0 1 0 1 0 1 1 0]
393
[1 0 0 1 0 1 0 1 1 0]
